# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-16 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0002_auto_20160409_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('hora_de_entrada', models.TimeField()),
                ('hora_de_salida', models.TimeField()),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'telefonos',
            },
        ),
        migrations.RemoveField(
            model_name='hospitales',
            name='hora_de_entrada',
        ),
        migrations.RemoveField(
            model_name='hospitales',
            name='hora_de_salida',
        ),
        migrations.AddField(
            model_name='telefonos',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitales.Hospitales'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitales.Hospitales'),
        ),
    ]
