# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-17 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0003_auto_20160416_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitales',
            new_name='Centros',
        ),
        migrations.RenameField(
            model_name='horarios',
            old_name='hospital',
            new_name='centro',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='hospital',
            new_name='centro',
        ),
        migrations.RenameField(
            model_name='telefonos',
            old_name='hospital',
            new_name='centro',
        ),
        migrations.AlterModelTable(
            name='centros',
            table='centros',
        ),
    ]
