# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-22 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0004_auto_20160416_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentrosPorHorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitales.Centros')),
            ],
            options={
                'db_table': 'centros_por_horario',
            },
        ),
        migrations.CreateModel(
            name='CentrosPorServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitales.Centros')),
            ],
            options={
                'db_table': 'centros_por_servicios',
            },
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='horarios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telefonos',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='centrosporservicios',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitales.Servicios'),
        ),
        migrations.AddField(
            model_name='centrosporhorarios',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitales.Horarios'),
        ),
    ]
