# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0005_auto_20160421_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='centros',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centros',
            name='fax',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrosporservicios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
