# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0007_auto_20160604_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
